organization: @AssistantNMS # org name on holopin
defaultSticker: clcuvyw02200208mgbwr3c6hj
stickers:
  - id: clcuvyw02200208mgbwr3c6hj
    alias: documentation-guru
  - id: clcuvrj0v029508mgjzgyr9y0
    alias: bug-finder
