name: assistantnms_app
description: Assistant for No Man's Sky
homepage: https://nmsassistant.com
# author: Kurt Lourens
version: 1.102.0+268
publish_to: 'none'

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: 1.0.4

  # AssistantApps
  assistantapps_flutter_common:
    git: https://github.com/AssistantApps/Flutter.Common.git
    # path: 'C:\Development\Projects\AssistantApps\assistantapps_flutter_common'

  # Firebase
  firebase_core: 1.13.1
  firebase_analytics: 9.1.2
  # firebase_analytics_web: 0.1.1
  firebase_messaging: 11.2.8
  firebase_auth: 3.3.9
  # firebase_auth_web: ^0.3.2+6

  # Redux
  flutter_redux: 0.8.2
  redux: 5.0.0

  # Google
  googleapis: 8.1.0
  googleapis_auth: 1.3.0
  google_sign_in: 5.2.4
  google_mobile_ads: 1.1.0

  # Push
  flutter_local_notifications: 9.4.0

  # UI
  adaptive_theme: 2.3.0
  adaptive_dialog: 1.4.0
  avatar_glow: 2.0.2
  assets_audio_player: 3.0.4+1
  bubble: 1.2.1
  bottom_bars: 1.1.0
  country_icons: 2.0.2 # Move to AA?
  custom_refresh_indicator: 1.0.0
  dots_indicator: 2.1.0
  expandable: 5.0.1
  ff_stars: 1.0.0
  flutter_simple_treeview: 3.0.1
  flutter_speed_dial: 5.0.0+1 # Move to AA?
  flutter_sticky_header: 0.6.1
  giffy_dialog: 1.8.0
  google_fonts: 2.3.1
  intro_slider: 3.0.3
  marquee_vertical: 1.0.0
  rflutter_alert: 2.0.4
  reorderables: 0.4.3
  swipe_to: 1.0.2
  websafe_svg: 2.1.1

  # Base
  get_it: 7.2.0
  http: 0.13.4
  connectivity_plus: 2.2.1

  # Misc
  timezone: 0.8.0
  flutter_native_timezone: 2.0.0
  enum_to_string: 2.0.1
  shared_preferences: 2.0.13
  shared_preferences_windows: 2.1.0
  after_layout: 1.1.0

  # logging
  talker: 0.8.0
  # talker_flutter: 0.8.0

  talker_flutter:
    git:
      url: https://github.com/AssistantApps/talker.git
      ref: master
      path: packages/talker_flutter/

dev_dependencies:
  flutter_launcher_icons: 0.9.2

dependency_overrides:
  google_fonts: 2.2.0
#   flutter_svg: ^0.23.0+1

flutter_icons: ## flutter pub run flutter_launcher_icons:main
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: 'assets/images/fullSizeIcon.png'
  adaptive_icon_background: 'assets/images/fullSizeIconAdaptiveBg.png'
  adaptive_icon_foreground: 'assets/images/fullSizeIconAdaptiveFg.png'

flutter:
  uses-material-design: true
  assets:
    - assets/lang/ # Languages

    - assets/json/ # BaseJson
    - assets/json/de/ # German
    - assets/json/en/ # English
    - assets/json/es/ # Spanish
    - assets/json/fr/ # French
    # - assets/json/hu/ # Hungarian
    # - assets/json/id/ # Indonesian
    - assets/json/it/ # Italian
    - assets/json/nl/ # Dutch
    - assets/json/pl/ # Polish
    - assets/json/pt-br/ # Portuguese
    - assets/json/pt/ # Portuguese
    # - assets/json/language.ro.json # Romanian
    - assets/json/ru/ # Russian
    # - assets/json/language.tr.json # Turkish
    # - assets/json/language.cs.json # Czech
    - assets/json/zh-hans/ # Simplified Chinese
    - assets/json/zh-hant/ # Traditional Chinese

    ## Guides
    - assets/guide/HowToMakeAGuide/
    - assets/guide/GlyphsAndPortals/
    - assets/guide/StarterGuide/
    - assets/guide/ShipsQuickReference/
    - assets/guide/MultiToolHunting/
    - assets/guide/FastUnitsAndNanites/
    - assets/guide/MultiToolGuide/
    - assets/guide/EverythingAboutBiomes/
    - assets/guide/EverythingAboutNanites/
    - assets/guide/EverythingAboutUnits/
    - assets/guide/Economy/
    - assets/guide/Translation/
    - assets/guide/StarshipsAndFreighters/
    - assets/guide/ScreenshotsGuide/
    - assets/guide/RememberingUniverses/
    - assets/guide/Crossplay/
    - assets/guide/TradeQuickReference/
    - assets/guide/AdvancedExoticShipHunting/
    - assets/guide/HowToGetSFreighter/

    # Audio
    - assets/audio/

    ## Data
    - assets/data/

    ## Images
    - assets/images/
    - assets/images/building/
    - assets/images/buttons/
    - assets/images/buttons/DS4/
    - assets/images/buttons/KEYBOARD/
    - assets/images/buttons/MOUSE/
    - assets/images/buttons/XBOX/
    - assets/images/constructedTechnology/
    - assets/images/cooking/
    - assets/images/contributors/
    - assets/images/curiosities/
    - assets/images/drawer/
    - assets/images/fab/
    - assets/images/faction/
    - assets/images/inventory/
    - assets/images/milestonePatches/
    - assets/images/milestonePatches/SPOOKWORM/
    - assets/images/journeyMilestones/
    - assets/images/other/
    - assets/images/portals/alt/
    - assets/images/portals/black/
    - assets/images/portals/white/
    - assets/images/proceduralProducts/
    - assets/images/products/
    - assets/images/rawMaterials/
    - assets/images/search/
    - assets/images/special/
    - assets/images/stats/
    - assets/images/technology/
    - assets/images/timer/
    - assets/images/titles/
    - assets/images/tradeItems/
    - assets/images/update/
    - assets/images/upgradeModules/
    - assets/images/weekendMission/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
    - family: nms
      fonts:
        - asset: assets/fonts/NoMansSky/NMSGeoSans_Kerned.ttf
    - family: expedition
      fonts:
        - asset: assets/fonts/ExpeditionAlphabet/NMSExpeditionAlphabet.ttf
