name: assistantnms_app
description: Assistant for No Man's Sky
homepage: https://nmsassistant.com
# author: Kurt Lourens
version: 2.6.0+302 # dart scripts\versionNumScript.dart
publish_to: 'none'

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # flutter_cupertino_localizations: ^1.0.1
  cupertino_icons: 1.0.4

  # AssistantApps
  assistantapps_flutter_common:
    # git: https://github.com/AssistantApps/Flutter.Common.git
    path: 'C:\Development\Projects\AssistantApps\assistantapps_flutter_common'

  # Google & Firebase
  firebase_core: 2.1.1
  firebase_analytics: 10.0.4
  # firebase_analytics_web: 0.1.1
  firebase_messaging: 14.0.4
  firebase_auth: 4.1.1
  # firebase_auth_web: ^0.3.2+6
  google_sign_in: 5.4.2
  google_mobile_ads: 2.2.0

  # Base
  get_it: 7.2.0
  connectivity_plus: 3.0.2
  flutter_redux: 0.10.0
  redux: 5.0.0

  # UI
  adaptive_theme: 3.1.1
  adaptive_dialog: 1.8.0+1
  avatar_glow: 2.0.2
  assets_audio_player: 3.0.4+3
  bitsdojo_window: 0.1.5
  bubble: 1.2.1
  dots_indicator: 2.1.0
  download: 0.0.1+1
  expandable: 5.0.1
  ff_stars: 1.2.5
  file_picker: 5.2.0+1
  flutter_image_slideshow: 0.1.4
  flutter_local_notifications: 11.0.1
  flutter_simple_treeview: 3.0.1
  flutter_speed_dial: 6.0.0
  flutter_sticky_header: 0.6.4
  intro_slider: 4.2.0
  marquee_vertical: 1.0.0
  pin_code_fields: 7.4.0
  rflutter_alert: 2.0.4
  reorderables: 0.5.0
  roll_slot_machine: ^1.0.0
  swipe_to: 1.0.2
  wiredash: 1.5.0

  # Misc
  timezone: 0.9.0
  flutter_native_timezone: 2.0.0
  enum_to_string: 2.0.1
  after_layout: 1.2.0

dev_dependencies:
  flutter_launcher_icons: 0.10.0
  msix: 3.6.3
  pubspec_parse: 1.2.1
  path: 1.8.2
  git: 2.0.0

dependency_overrides:
  win32: 3.0.0

flutter_icons: ## flutter pub run flutter_launcher_icons:main
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: 'assets/images/fullSizeIcon.png'
  adaptive_icon_background: 'assets/images/fullSizeIconAdaptiveBg.png'
  adaptive_icon_foreground: 'assets/images/fullSizeIconAdaptiveFg.png'

# flutter pub run msix:create
msix_config: # https://pub.dev/documentation/msix/latest/
  display_name: Assistant for No Man's Sky
  publisher_display_name: AssistantApps
  msix_version: 2.6.0.0
  identity_name: notSureIfSecret
  publisher: notSureIfSecret
  logo_path: './assets/images/fullSizeIcon.png'
  languages: en
  capabilities: internetClient
  store: true

flutter:
  uses-material-design: true
  assets:
    - assets/lang/ # Languages

    - assets/json/ # BaseJson
    - assets/json/de/ # German
    - assets/json/en/ # English
    - assets/json/es/ # Spanish
    - assets/json/fr/ # French
    - assets/json/it/ # Italian
    - assets/json/nl/ # Dutch
    - assets/json/pl/ # Polish
    - assets/json/pt-br/ # Portuguese
    - assets/json/pt/ # Portuguese
    - assets/json/ru/ # Russian
    - assets/json/zh-hans/ # Simplified Chinese
    - assets/json/zh-hant/ # Traditional Chinese

    ## Guides
    - assets/guide/HowToMakeAGuide/
    - assets/guide/GlyphsAndPortals/
    - assets/guide/StarterGuide/
    - assets/guide/ShipsQuickReference/
    - assets/guide/MultiToolHunting/
    - assets/guide/FastUnitsAndNanites/
    - assets/guide/MultiToolGuide/
    - assets/guide/EverythingAboutBiomes/
    - assets/guide/EverythingAboutNanites/
    - assets/guide/EverythingAboutUnits/
    - assets/guide/Economy/
    - assets/guide/Translation/
    - assets/guide/StarshipsAndFreighters/
    - assets/guide/ScreenshotsGuide/
    - assets/guide/RememberingUniverses/
    - assets/guide/Crossplay/
    - assets/guide/TradeQuickReference/
    - assets/guide/AdvancedExoticShipHunting/
    - assets/guide/HowToGetSFreighter/
    - assets/guide/HowToGetLivingShip/
    - assets/guide/TheLoreAndPlot/

    # Audio
    - assets/audio/

    ## Data
    - assets/data/

    ## Images
    - assets/images/
    - assets/images/building/
    - assets/images/buttons/
    - assets/images/buttons/ACTIONS/
    - assets/images/buttons/DS4/
    - assets/images/buttons/KEYBOARD/
    - assets/images/buttons/MOUSE/
    - assets/images/buttons/SWITCH/
    - assets/images/buttons/XBOX/
    - assets/images/constructedTechnology/
    - assets/images/cooking/
    - assets/images/contributors/
    - assets/images/curiosities/
    - assets/images/drawer/
    - assets/images/fab/
    - assets/images/faction/
    - assets/images/inventory/
    - assets/images/milestonePatches/
    - assets/images/milestonePatches/SPOOKWORM/
    - assets/images/journeyMilestones/
    - assets/images/other/
    - assets/images/portals/alt/
    - assets/images/portals/black/
    - assets/images/portals/white/
    - assets/images/proceduralProducts/
    - assets/images/products/
    - assets/images/rawMaterials/
    - assets/images/search/
    - assets/images/special/
    - assets/images/stats/
    - assets/images/technology/
    - assets/images/timer/
    - assets/images/titles/
    - assets/images/tradeItems/
    - assets/images/update/
    - assets/images/upgradeModules/
    - assets/images/weekendMission/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
    - family: nms
      fonts:
        - asset: assets/fonts/NoMansSky/NMSGeoSans_Kerned.ttf
    - family: expedition
      fonts:
        - asset: assets/fonts/ExpeditionAlphabet/NMSExpeditionAlphabet.ttf
