import 'package:assistantapps_flutter_common/assistantapps_flutter_common.dart';

List<LocalizationMap> supportedLanguageMaps = [
  LocalizationMap(LocaleKey.english, 'en', 'gb', percentageComplete: 100),
  LocalizationMap(LocaleKey.dutch, 'nl', 'nl', percentageComplete: 59),
  LocalizationMap(LocaleKey.german, 'de', 'de', percentageComplete: 99),
  LocalizationMap(LocaleKey.french, 'fr', 'fr', percentageComplete: 99),
  LocalizationMap(LocaleKey.italian, 'it', 'it', percentageComplete: 99),
  LocalizationMap(LocaleKey.russian, 'ru', 'ru', percentageComplete: 98),
  LocalizationMap(LocaleKey.polish, 'pl', 'pl', percentageComplete: 99),
  LocalizationMap(LocaleKey.brazilianPortuguese, 'pt-br', 'br',
      percentageComplete: 97),
  LocalizationMap(LocaleKey.portuguese, 'pt', 'pt', percentageComplete: 25),
  LocalizationMap(LocaleKey.norwegian, 'no', 'no', percentageComplete: 86),
  LocalizationMap(LocaleKey.romanian, 'ro', 'ro', percentageComplete: 31),
  LocalizationMap(LocaleKey.spanish, 'es', 'es', percentageComplete: 98),
  LocalizationMap(LocaleKey.czech, 'cs', 'cz', percentageComplete: 98),
  LocalizationMap(LocaleKey.turkish, 'tr', 'tr', percentageComplete: 97),
  LocalizationMap(LocaleKey.hungarian, 'hu', 'hu', percentageComplete: 98),
  LocalizationMap(LocaleKey.simplifiedChinese, 'zh-hans', 'cn',
      percentageComplete: 99),
  LocalizationMap(LocaleKey.traditionalChinese, 'zh-hant', 'cn',
      percentageComplete: 34),
  LocalizationMap(LocaleKey.arabic, 'ar', 'ar', percentageComplete: 12),
  LocalizationMap(LocaleKey.vietnamese, 'vi-vn', 'vn', percentageComplete: 99),
  LocalizationMap(LocaleKey.urdu, 'ur', 'pk', percentageComplete: 7),
  LocalizationMap(LocaleKey.filipino, 'ph', 'ph', percentageComplete: 0),
  LocalizationMap(LocaleKey.indonesian, 'id', 'id', percentageComplete: 97),
  LocalizationMap(LocaleKey.malaysian, 'ms', 'my', percentageComplete: 97),
  LocalizationMap(LocaleKey.tagalog, 'tl', 'ph', percentageComplete: 0),
  LocalizationMap(LocaleKey.japanese, 'ja', 'jp', percentageComplete: 0),
  LocalizationMap(LocaleKey.afrikaans, 'af', 'za', percentageComplete: 32),
];
