class UserSelectionIcons {
  static const List<String> nomNomInventoryTypeIcons = [
    'decal0.png', // Unknown,
    'special0.png', // Exosuit,
    'decal0.png', // Starship, // TODO replace
    'vehicle1.png', // Roamer,
    'vehicle5.png', // Nomad,
    'vehicle2.png', // Pilgrim,
    'vehicle4.png', // Colossus,
    'vehicle6.png', // Minotaur,
    'vehicle3.png', // Nautilon,
    'freighter9.png', // Freighter,  // TODO replace
    'container0.png', // StorageContainer0,
    'container1.png', // StorageContainer1,
    'container2.png', // StorageContainer2,
    'container3.png', // StorageContainer3,
    'container4.png', // StorageContainer4,
    'container5.png', // StorageContainer5,
    'container6.png', // StorageContainer6,
    'container7.png', // StorageContainer7,
    'container8.png', // StorageContainer8,
    'container9.png', // StorageContainer9,
    'container9.png', // StorageContainer9,
  ];

  static const List<String> inventory = [
    'decal0.png',
    'decal1.png',
    'decal2.png',
    'decal3.png',
    'decal4.png',
    'decal5.png',
    'decal6.png',
    'decal7.png',
    'decal8.png',
    'decal9.png',
    'container0.png',
    'container1.png',
    'container2.png',
    'container3.png',
    'container4.png',
    'container5.png',
    'container6.png',
    'container7.png',
    'container8.png',
    'container9.png',
    'freighter0.png',
    'freighter1.png',
    'freighter2.png',
    'freighter3.png',
    'freighter4.png',
    'freighter5.png',
    'freighter6.png',
    'freighter7.png',
    'freighter8.png',
    'freighter9.png',
    'decala.png',
    'decalb.png',
    'decalc.png',
    'decald.png',
    'decale.png',
    'decalf.png',
    'decalg.png',
    'decalh.png',
    'decali.png',
    'cooking.png',
    'special0.png',
    'special1.png',
    'special2.png',
    'special3.png',
    'special4.png',
    'special5.png',
    'special6.png',
    'special7.png',
    'special8.png',
    'vehicle1.png',
    'vehicle2.png',
    'vehicle3.png',
    'vehicle4.png',
    'vehicle5.png',
    'vehicle6.png'
  ];

  static const List<String> timer = [
    'timer/frigate1.png',
    'timer/frigate2.png',
    'timer/frigate3.png',
    'timer/frigate4.png',
    'timer/frigate5.png',
    'timer/freighter.png',
    'timer/classa.png',
    'timer/classb.png',
    'timer/classc.png',
    'timer/classs.png',
    'products/82.png',
    'products/86.png',
    'products/83.png',
    'products/87.png',
    'products/84.png',
    'products/88.png',
    'products/85.png',
    'products/89.png',
    'building/129.png',
    'building/130.png',
    'building/131.png',
    'building/132.png',
    'building/133.png',
    'building/134.png',
    'building/135.png',
    'building/136.png',
    'building/137.png',
    'building/138.png',
    'building/139.png',
    'building/140.png',
    'constructedTechnology/17.png',
    'constructedTechnology/33.png',
    'constructedTechnology/34.png',
    'constructedTechnology/13.png',
    'constructedTechnology/14.png',
    'constructedTechnology/15.png',
    'constructedTechnology/16.png',
    'inventory/decala.png',
    'inventory/decalb.png',
    'inventory/decalc.png',
    'inventory/decald.png',
    'inventory/decale.png',
    'inventory/decalf.png',
    'inventory/decalg.png',
    'inventory/decalh.png',
    'inventory/decali.png',
    'inventory/special0.png',
    'inventory/special1.png',
    'inventory/special2.png',
    'inventory/special3.png',
    'inventory/special4.png',
    'inventory/special5.png',
    'inventory/special6.png',
    'inventory/special7.png',
    'inventory/special8.png',
  ];
}
