name: '🐛 Bug Report'
description: |
  Thank you for reporting issues!
  Please make sure that you have looked at and read the "I found a Bug and I want to report it" section of the Contributing guide!
title: '🐛 Bug Report: '
labels: bug
body:
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: 📜 Describe the bug
      description: |
        A clear and concise description of what the bug is. If you for example disagree with what the name of an game item is please point out what you believe it should say.
      placeholder: 🐛🐜🪲
  - type: textarea
    id: steps-to-reproduce
    validations:
      required: true
    attributes:
      label: 👟 To Reproduce
      description: |
        Steps to reproduce the behavior:
      value: |
        1. Go to 'Bone Cream' item page
        2. Click on add to cart button
        3. Give a quantity
        4. It fails to add to cart
  - type: textarea
    id: expected
    validations:
      required: true
    attributes:
      label: 👍 Expected behavior
      description: |
        A clear and concise description of what you expected to happen.
  - type: dropdown
    id: device
    validations:
      required: true
    attributes:
      label: 📱 Where did you find this problem?
      multiple: true
      options:
        - Android
        - iOS
        - Windows
        - WebApp
  - type: textarea
    id: logs
    attributes:
      label: 🪵 Logs
      description: |
        Please recreate the issue and attach/paste the logs from the app onto this issue. You can find the logs on the settings page, there is a "Logs" option.
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: '👀 Have you checked if this bug report has been created already?'
      options:
        - label: "I checked and couldn't find similar issue"
          required: true
  - type: checkboxes
    id: read-code-of-conduct
    attributes:
      label: '🏢 Have you read the Code of Conduct?'
      options:
        - label: 'I have read the [Code of Conduct](https://github.com/AssistantNMS/App/blob/main/.github/CODE_OF_CONDUCT.md)'
          required: true
  - type: dropdown
    attributes:
      label: Are you willing to submit PR?
      description: This is absolutely not required, but we are happy to guide you in the contribution process.
      options:
        - Yes I am willing to submit a PR!
        - No, but I'm happy to collaborate on a PR with someone else
        - No, I don't have time to work on this right now
