name: "🚀 Feature request"
description: Suggest an idea for this project
title: '🚀 Feature request: '
labels: idea
body:
  - type: markdown
    attributes:
      value: |
        _**Please note:** Just because a feature ticket exists, does not mean that we will or can build the feature. A feature may also require research before work on it can even start._
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: 🔖 Describe the solution you'd like
      description: |
        A clear and concise description of what you want to happen.
  - type: textarea
    id: alternatives
    attributes:
      label: 🩹 Describe alternatives you've considered
      description: |
        A clear and concise description of any alternative solutions or features you've considered.
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: '👀 Have you checked if this bug report has been created already?'
      options:
        - label: "I checked and couldn't find similar issue"
          required: true
  - type: checkboxes
    id: read-code-of-conduct
    attributes:
      label: '🏢 Have you read the Code of Conduct?'
      options:
        - label: 'I have read the [Code of Conduct](https://github.com/AssistantNMS/App/blob/main/.github/CODE_OF_CONDUCT.md)'
          required: true
  - type: dropdown
    attributes:
      label: Are you willing to submit PR?
      description: This is absolutely not required, but we are happy to guide you in the contribution process.
      options:
        - Yes I am willing to submit a PR!
        - No, but I'm happy to collaborate on a PR with someone else
        - No, I don't have time to work on this right now
