// ignore_for_file: constant_identifier_names

import 'package:assistantapps_flutter_common/assistantapps_flutter_common.dart';

enum AlienPuzzleRewardItemType {
  Unknown,
  Product,
  ProductRecipe,
  Technology,
  TechnologyRecipe,
  Mission,
  Standing,
  Scan,
  SignalScan,
  ProceduralProduct,
  ProceduralTechnology,
  DamagedTech,
  RepairKit,
  NewWord,
  Money,
  Damage,
  TechTree,
  Health,
  Hazard,
  Weapon,
  Shield,
  ScanEvent,
}

final alienPuzzleRewardItemTypeValues = EnumValues({
  "Unknown": AlienPuzzleRewardItemType.Unknown,
  "Product": AlienPuzzleRewardItemType.Product,
  "ProductRecipe": AlienPuzzleRewardItemType.ProductRecipe,
  "Technology": AlienPuzzleRewardItemType.Technology,
  "TechnologyRecipe": AlienPuzzleRewardItemType.TechnologyRecipe,
  "Mission": AlienPuzzleRewardItemType.Mission,
  "Standing": AlienPuzzleRewardItemType.Standing,
  "Scan": AlienPuzzleRewardItemType.Scan,
  "SignalScan": AlienPuzzleRewardItemType.SignalScan,
  "ProceduralProduct": AlienPuzzleRewardItemType.ProceduralProduct,
  "ProceduralTechnology": AlienPuzzleRewardItemType.ProceduralTechnology,
  "DamagedTech": AlienPuzzleRewardItemType.DamagedTech,
  "RepairKit": AlienPuzzleRewardItemType.RepairKit,
  "NewWord": AlienPuzzleRewardItemType.NewWord,
  "Money": AlienPuzzleRewardItemType.Money,
  "Damage": AlienPuzzleRewardItemType.Damage,
  "TechTree": AlienPuzzleRewardItemType.TechTree,
  "Health": AlienPuzzleRewardItemType.Health,
  "Hazard": AlienPuzzleRewardItemType.Hazard,
  "Weapon": AlienPuzzleRewardItemType.Weapon,
  "Shield": AlienPuzzleRewardItemType.Shield,
  "ScanEvent": AlienPuzzleRewardItemType.ScanEvent,
});
